// Reads assets/eip-8182/poseidon2_bn254_t4_rf8_rp56.json and emits a
// Circom file with the round constants and internal-diagonal embedded.
// Run: node scripts/circom/gen_poseidon2_constants.js > circuits/common/poseidon2_constants.circom

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '../..');
const ASSET = path.join(ROOT, 'assets/eip-8182/poseidon2_bn254_t4_rf8_rp56.json');
const params = JSON.parse(fs.readFileSync(ASSET, 'utf8'));

const RF = params.fullRounds;       // 8
const RP = params.partialRounds;    // 56
const T  = params.stateWidth;       // 4
const HALF_RF = RF / 2;             // 4

if (params.roundConstants.length !== RF * T + RP) {
  throw new Error(`expected ${RF*T + RP} constants, got ${params.roundConstants.length}`);
}
if (params.internalDiagonal.length !== T) {
  throw new Error(`expected ${T} internal-diagonal entries, got ${params.internalDiagonal.length}`);
}

// Layout:
//   [0 .. HALF_RF*T)        first-half full-round constants (T per round)
//   [HALF_RF*T .. +RP)      partial-round constants (1 per round)
//   [HALF_RF*T+RP .. +HALF_RF*T)  second-half full-round constants
const firstFull   = params.roundConstants.slice(0, HALF_RF * T);
const partial     = params.roundConstants.slice(HALF_RF * T, HALF_RF * T + RP);
const secondFull  = params.roundConstants.slice(HALF_RF * T + RP);

if (secondFull.length !== HALF_RF * T) {
  throw new Error(`partition off: secondFull len ${secondFull.length}`);
}

const lines = [];
lines.push('// Auto-generated by scripts/gen_poseidon2_constants.js');
lines.push('// Source: assets/eip-8182/poseidon2_bn254_t4_rf8_rp56.json');
lines.push('// DO NOT EDIT BY HAND.');
lines.push('');
lines.push('pragma circom 2.0.0;');
lines.push('');
lines.push(`// stateWidth t=${T}, rate=3, capacity=1, RF=${RF}, RP=${RP}, sbox=x^5`);
lines.push('');
lines.push(`function POSEIDON2_T() { return ${T}; }`);
lines.push(`function POSEIDON2_RF_HALF() { return ${HALF_RF}; }`);
lines.push(`function POSEIDON2_RP() { return ${RP}; }`);
lines.push('');

// Internal diagonal: M_I = I + diag(internalDiagonal). The mat-mul is
// y_i = sum(state) + internalDiagonal[i] * state[i]
lines.push(`function POSEIDON2_INT_DIAG(i) {`);
lines.push(`    var d[${T}];`);
params.internalDiagonal.forEach((v, i) => {
  lines.push(`    d[${i}] = ${BigInt(v).toString()};`);
});
lines.push(`    return d[i];`);
lines.push(`}`);
lines.push('');

function emitConstantsArray(name, list) {
  lines.push(`function ${name}(i) {`);
  lines.push(`    var c[${list.length}];`);
  list.forEach((v, i) => {
    lines.push(`    c[${i}] = ${BigInt(v).toString()};`);
  });
  lines.push(`    return c[i];`);
  lines.push(`}`);
  lines.push('');
}

// First-half full-round constants: index by round (0..HALF_RF-1) and slot (0..T-1)
//   POSEIDON2_RC_FULL_FIRST(r * T + s)
emitConstantsArray('POSEIDON2_RC_FULL_FIRST', firstFull);

// Partial-round constants: index by round (0..RP-1)
//   POSEIDON2_RC_PARTIAL(r)
emitConstantsArray('POSEIDON2_RC_PARTIAL', partial);

// Second-half full-round constants
//   POSEIDON2_RC_FULL_SECOND(r * T + s)
emitConstantsArray('POSEIDON2_RC_FULL_SECOND', secondFull);

console.log(lines.join('\n'));
