// Compute Section 3.1 domain tags: keccak256("eip-8182.<context>") mod p_bn254.
// Emits both circuits/common/domain_tags.circom and build/domain_tags.json
// for the witness generator.
//
// Run: node scripts/circom/gen_domain_tags.js

const fs = require('fs');
const path = require('path');
const { keccak256 } = require('ethereum-cryptography/keccak');
const { utf8ToBytes, bytesToHex } = require('ethereum-cryptography/utils');

const ROOT = path.resolve(__dirname, '../..');

const P = BigInt('0x30644e72e131a029b85045b68181585d2833e84879b9709143e1f593f0000001');

const CONTEXTS = [
  ['OWNER_NULLIFIER_KEY_HASH_DOMAIN', 'owner_nullifier_key_hash'],
  ['OWNER_COMMITMENT_DOMAIN',         'owner_commitment'],
  ['NOTE_BODY_COMMITMENT_DOMAIN',     'note_body_commitment'],
  ['NOTE_COMMITMENT_DOMAIN',          'note_commitment'],
  ['NULLIFIER_DOMAIN',                'nullifier'],
  ['PHANTOM_NULLIFIER_DOMAIN',        'phantom_nullifier'],
  ['INTENT_REPLAY_ID_DOMAIN',         'intent_replay_id'],
  ['TRANSACT_NOTE_SECRET_DOMAIN',     'transact_note_secret'],
  ['NOTE_SECRET_SEED_DOMAIN',         'note_secret_seed'],
  ['TRANSACTION_INTENT_DIGEST_DOMAIN','transaction_intent_digest'],
  ['OUTPUT_BINDING_DOMAIN',           'output_binding'],
  ['AUTH_POLICY_DOMAIN',              'auth_policy'],
  ['POLICY_COMMITMENT_DOMAIN',        'policy_commitment'],
  ['BLINDED_AUTH_COMMITMENT_DOMAIN',  'blinded_auth_commitment'],
  ['USER_REGISTRY_LEAF_DOMAIN',       'user_registry_leaf'],
];

const tags = {};
for (const [name, ctx] of CONTEXTS) {
  const h = keccak256(utf8ToBytes('eip-8182.' + ctx));
  const v = BigInt('0x' + bytesToHex(h)) % P;
  tags[name] = v;
}

const lines = [];
lines.push('// Auto-generated by scripts/gen_domain_tags.js');
lines.push('// keccak256("eip-8182.<context>") mod p_bn254');
lines.push('');
lines.push('pragma circom 2.0.0;');
lines.push('');
for (const [name] of CONTEXTS) {
  lines.push(`function ${name}() { return ${tags[name].toString()}; }`);
}
fs.mkdirSync(path.join(ROOT, 'build'), { recursive: true });
fs.writeFileSync(
  path.join(ROOT, 'circuits/common/domain_tags.circom'),
  lines.join('\n') + '\n'
);

const jsonOut = {};
for (const [name] of CONTEXTS) jsonOut[name] = '0x' + tags[name].toString(16);
fs.writeFileSync(
  path.join(ROOT, 'build/domain_tags.json'),
  JSON.stringify(jsonOut, null, 2) + '\n'
);

console.log('wrote circuits/common/domain_tags.circom and build/domain_tags.json');
for (const [name] of CONTEXTS) {
  console.log(`  ${name} = 0x${tags[name].toString(16)}`);
}
