// This file is generated by scripts/generate-domain-constants.mjs.
// Do not edit it by hand.

import { keccak_256 } from '@noble/hashes/sha3'
import { utf8ToBytes } from '@noble/hashes/utils'

export const FIELD_MODULUS =
  21888242871839275222246405745257275088548364400416034343698204186575808495617n

export const DOMAIN_CONTEXTS = {
  NULLIFIER_DOMAIN: 'nullifier',
  PHANTOM_DOMAIN: 'phantom',
  ORIGIN_TAG_DOMAIN: 'origin_tag',
  INTENT_DOMAIN: 'intent',
  NK_DOMAIN: 'nk',
  RANDOMNESS_DOMAIN: 'randomness',
  INTENT_DIGEST_DOMAIN: 'intent_digest',
  OUTPUT_BINDING_DOMAIN: 'output_binding',
  AUTH_POLICY_DOMAIN: 'auth_policy',
  AUTH_POLICY_KEY_DOMAIN: 'auth_policy_key',
  AUTH_VK_DOMAIN: 'auth_vk',
  OUTPUT_SECRET_DOMAIN: 'output_secret',
  USER_REGISTRY_LEAF_DOMAIN: 'user_registry_leaf',
} as const

function bytesToBigInt(bytes: Uint8Array): bigint {
  let result = 0n
  for (const byte of bytes) {
    result = (result << 8n) | BigInt(byte)
  }
  return result
}

export function deriveEip8182Domain(contextName: string): bigint {
  return bytesToBigInt(keccak_256(utf8ToBytes(`eip-8182.${contextName}`))) % FIELD_MODULUS
}

export const NULLIFIER_DOMAIN = deriveEip8182Domain(DOMAIN_CONTEXTS.NULLIFIER_DOMAIN)
export const PHANTOM_DOMAIN = deriveEip8182Domain(DOMAIN_CONTEXTS.PHANTOM_DOMAIN)
export const ORIGIN_TAG_DOMAIN = deriveEip8182Domain(DOMAIN_CONTEXTS.ORIGIN_TAG_DOMAIN)
export const INTENT_DOMAIN = deriveEip8182Domain(DOMAIN_CONTEXTS.INTENT_DOMAIN)
export const NK_DOMAIN = deriveEip8182Domain(DOMAIN_CONTEXTS.NK_DOMAIN)
export const RANDOMNESS_DOMAIN = deriveEip8182Domain(DOMAIN_CONTEXTS.RANDOMNESS_DOMAIN)
export const INTENT_DIGEST_DOMAIN = deriveEip8182Domain(DOMAIN_CONTEXTS.INTENT_DIGEST_DOMAIN)
export const OUTPUT_BINDING_DOMAIN = deriveEip8182Domain(DOMAIN_CONTEXTS.OUTPUT_BINDING_DOMAIN)
export const AUTH_POLICY_DOMAIN = deriveEip8182Domain(DOMAIN_CONTEXTS.AUTH_POLICY_DOMAIN)
export const AUTH_POLICY_KEY_DOMAIN = deriveEip8182Domain(DOMAIN_CONTEXTS.AUTH_POLICY_KEY_DOMAIN)
export const AUTH_VK_DOMAIN = deriveEip8182Domain(DOMAIN_CONTEXTS.AUTH_VK_DOMAIN)
export const OUTPUT_SECRET_DOMAIN = deriveEip8182Domain(DOMAIN_CONTEXTS.OUTPUT_SECRET_DOMAIN)
export const USER_REGISTRY_LEAF_DOMAIN = deriveEip8182Domain(DOMAIN_CONTEXTS.USER_REGISTRY_LEAF_DOMAIN)
