// This file is generated by scripts/generate-domain-constants.mjs.
// Do not edit it by hand.

import { keccak_256 } from '@noble/hashes/sha3'
import { utf8ToBytes } from '@noble/hashes/utils'

export const FIELD_MODULUS =
  21888242871839275222246405745257275088548364400416034343698204186575808495617n

export const DOMAIN_CONTEXTS = {
  NOTE_NULLIFIER_DOMAIN: 'note_nullifier',
  PHANTOM_NULLIFIER_DOMAIN: 'phantom_nullifier',
  ORIGIN_TAG_DOMAIN: 'origin_tag',
  TRANSACTION_REPLAY_ID_DOMAIN: 'transaction_replay_id',
  OWNER_NULLIFIER_KEY_HASH_DOMAIN: 'owner_nullifier_key_hash',
  NOTE_SECRET_DOMAIN: 'note_secret',
  TRANSACTION_INTENT_DIGEST_DOMAIN: 'transaction_intent_digest',
  OUTPUT_BINDING_DOMAIN: 'output_binding',
  AUTH_POLICY_DOMAIN: 'auth_policy',
  AUTH_POLICY_KEY_DOMAIN: 'auth_policy_key',
  AUTH_VK_DOMAIN: 'auth_vk',
  NOTE_SECRET_SEED_DOMAIN: 'note_secret_seed',
  USER_REGISTRY_LEAF_DOMAIN: 'user_registry_leaf',
} as const

function bytesToBigInt(bytes: Uint8Array): bigint {
  let result = 0n
  for (const byte of bytes) {
    result = (result << 8n) | BigInt(byte)
  }
  return result
}

export function deriveEip8182Domain(contextName: string): bigint {
  return bytesToBigInt(keccak_256(utf8ToBytes(`eip-8182.${contextName}`))) % FIELD_MODULUS
}

export const NOTE_NULLIFIER_DOMAIN = deriveEip8182Domain(DOMAIN_CONTEXTS.NOTE_NULLIFIER_DOMAIN)
export const PHANTOM_NULLIFIER_DOMAIN = deriveEip8182Domain(DOMAIN_CONTEXTS.PHANTOM_NULLIFIER_DOMAIN)
export const ORIGIN_TAG_DOMAIN = deriveEip8182Domain(DOMAIN_CONTEXTS.ORIGIN_TAG_DOMAIN)
export const TRANSACTION_REPLAY_ID_DOMAIN = deriveEip8182Domain(DOMAIN_CONTEXTS.TRANSACTION_REPLAY_ID_DOMAIN)
export const OWNER_NULLIFIER_KEY_HASH_DOMAIN = deriveEip8182Domain(DOMAIN_CONTEXTS.OWNER_NULLIFIER_KEY_HASH_DOMAIN)
export const NOTE_SECRET_DOMAIN = deriveEip8182Domain(DOMAIN_CONTEXTS.NOTE_SECRET_DOMAIN)
export const TRANSACTION_INTENT_DIGEST_DOMAIN = deriveEip8182Domain(DOMAIN_CONTEXTS.TRANSACTION_INTENT_DIGEST_DOMAIN)
export const OUTPUT_BINDING_DOMAIN = deriveEip8182Domain(DOMAIN_CONTEXTS.OUTPUT_BINDING_DOMAIN)
export const AUTH_POLICY_DOMAIN = deriveEip8182Domain(DOMAIN_CONTEXTS.AUTH_POLICY_DOMAIN)
export const AUTH_POLICY_KEY_DOMAIN = deriveEip8182Domain(DOMAIN_CONTEXTS.AUTH_POLICY_KEY_DOMAIN)
export const AUTH_VK_DOMAIN = deriveEip8182Domain(DOMAIN_CONTEXTS.AUTH_VK_DOMAIN)
export const NOTE_SECRET_SEED_DOMAIN = deriveEip8182Domain(DOMAIN_CONTEXTS.NOTE_SECRET_SEED_DOMAIN)
export const USER_REGISTRY_LEAF_DOMAIN = deriveEip8182Domain(DOMAIN_CONTEXTS.USER_REGISTRY_LEAF_DOMAIN)
