#!/usr/bin/env node
// Negative-witness tests for the pool circuit (spec §"Test Cases" subset).
//
// Strategy: load the worst-case happy-path witness from build/pool/input.json
// (generated by gen_pool_witness_input.js), apply a single targeted mutation
// per case that violates exactly one normative constraint, run the wasm
// witness generator, and assert it fails. Any case that passes is a
// soundness gap.
//
// Usage:
//   node scripts/witness/gen_pool_witness_input.js   # produce baseline first
//   node scripts/witness/negative_test.js
//
// Exit code 0 = all negatives correctly rejected; 1 = at least one passed
// when it should have failed.

const fs   = require('fs');
const path = require('path');
const os   = require('os');
const { spawnSync } = require('child_process');

const ROOT      = path.resolve(__dirname, '../..');
const POOL_DIR  = path.join(ROOT, 'build/pool');
const BASE_JSON = path.join(POOL_DIR, 'input.json');
const WASM      = path.join(POOL_DIR, 'pool_js/pool.wasm');
const WGEN      = path.join(POOL_DIR, 'pool_js/generate_witness.js');

if (!fs.existsSync(BASE_JSON)) {
  console.error(`baseline witness ${BASE_JSON} missing — run gen_pool_witness_input.js first`);
  process.exit(2);
}

const BASE = JSON.parse(fs.readFileSync(BASE_JSON, 'utf8'));

// Shallow clone with array-of-arrays cloning (witnesses have nested arrays).
function clone(o) {
  return JSON.parse(JSON.stringify(o));
}

// Run the wasm witness generator on `input` and return { ok, stderr }.
//   ok === true  iff witness generation succeeded (constraints satisfied)
//   ok === false iff constraint violation or other rejection
function tryGenerateWitness(input) {
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'eip8182-neg-'));
  const inPath  = path.join(tmp, 'input.json');
  const outPath = path.join(tmp, 'witness.wtns');
  fs.writeFileSync(inPath, JSON.stringify(input));
  try {
    const r = spawnSync('node', [WGEN, WASM, inPath, outPath], { encoding: 'utf8' });
    return { ok: r.status === 0, stderr: r.stderr || r.stdout || '' };
  } finally {
    fs.rmSync(tmp, { recursive: true, force: true });
  }
}

// ---- Negative cases ----
// Each case: { name, mutate(input), expect: <substring of expected stderr or '*' for any failure> }
const cases = [
  {
    name: 'dummy output with non-zero amount (slot 1)',
    mutate: (i) => {
      i.outIsReal[1] = '0';            // make slot 1 dummy
      // amount left non-zero -> should fail (1 - outIsReal[1]) * outAmount[1] === 0
      i.outAmount[1] = '7';
      return i;
    },
  },
  {
    name: 'dummy output with non-DUMMY ownerNullifierKeyHash (slot 1)',
    mutate: (i) => {
      i.outIsReal[1] = '0';
      i.outAmount[1] = '0';            // satisfy the amount constraint
      // outOwnerNullifierKeyHash[1] is the sender's hash in the baseline,
      // which is NOT the DUMMY hash -> should fail dummy-owner constraint.
      // Also need to satisfy value conservation: input total stays 15,
      // output 0+slot2 totals 8+2 = 10 < 15. Fix by adjusting outAmount[0].
      i.outAmount[0] = '13';
      return i;
    },
  },
  {
    name: 'real output with amount = 0 (slot 0)',
    mutate: (i) => {
      // Keep slot 0 real but set amount = 0 -> fails real-amount-positive.
      // Adjust value conservation: inputs 15, outputs slot1+slot2=5+2=7,
      // need 8 more to reach 15; rebalance slot 1 to 13.
      i.outAmount[0] = '0';
      i.outAmount[1] = '13';
      return i;
    },
  },
  {
    name: 'both inputs phantom (no real input)',
    mutate: (i) => {
      i.inIsReal = ['0', '0'];
      i.inAmount = ['0', '0'];
      // value conservation must still hold; zero outputs/public.
      i.outAmount = ['0', '0', '0'];
      i.outIsReal = ['1', '0', '0'];   // keep transfer-mode slot-0-real
      return i;
    },
  },
  {
    name: 'phantom input with non-zero amount',
    mutate: (i) => {
      i.inIsReal[0] = '0';
      // amount left non-zero -> fails phantom-amount-zero
      // value conservation would also break, but constraint fires first
      return i;
    },
  },
  {
    name: 'transfer with outRecipient[0] != recipientAddress',
    mutate: (i) => {
      // Redirect slot-0 payment to a different address; in transfer mode
      // (operationKind derived from publicAmountOut == 0), this fails the
      // outRecipient[0] === recipientAddress binding.
      i.outRecipient[0] = '0x9999999999999999999999999999999999999999';
      return i;
    },
  },
  {
    name: 'reserved flag bit 3 set',
    mutate: (i) => {
      // baseline executionConstraintsFlags = 7 (bits 0/1/2 set);
      // setting bit 3 -> 15 should fail reserved-bit-zero check.
      i.executionConstraintsFlags = '15';
      return i;
    },
  },
  {
    name: 'lockedOutputBinding[0] != 0 with flag bit 0 = 0',
    mutate: (i) => {
      // Flip flag to 6 (bits 1,2 set, bit 0 unset) but keep slot-0 lock value.
      // -> (1 - flagBit_0) * locked[0] !== 0
      i.executionConstraintsFlags = '6';
      // Update digest? Actually no — this script tests the wasm constraint
      // generator only; the digest mismatch fires inside the same circuit
      // run, so any constraint failure (digest or flag-lock) counts as
      // correct rejection. Both should fire here.
      return i;
    },
  },
  {
    name: 'real input/output token != canonical (membership fails)',
    mutate: (i) => {
      // The on-tree input notes were committed with the original tokenAddress
      // baked into noteCommitmentRoot. Mutating the canonical tokenAddress
      // witness re-derives in-circuit input bodies with a different token,
      // so the recomputed note commitments no longer reconstruct to
      // noteCommitmentRoot — Merkle membership fails for both real inputs.
      // Implicitly also breaks the digest, so multiple constraints fire;
      // any one rejection is sufficient evidence the canonical-token chain
      // is wired correctly.
      i.tokenAddress = '0x9999999999999999999999999999999999999999';
      return i;
    },
  },
  {
    name: 'real slot 2 with feeNoteRecipientAddress = 0',
    mutate: (i) => {
      // Spec §9.5: when slot 2 is real, feeNoteRecipientAddress MUST be
      // nonzero. This was previously enforced only indirectly via
      // recipient-registry membership for outRecipient[2]. The new direct
      // constraint must reject feeNoteRecipientAddress = 0 here.
      // Set outRecipient[2] to 0 too so the (outRecipient[2] -
      // feeNoteRecipientAddress) constraint is satisfied; the new
      // outIsReal[2] * feeNoteRecipIsZero.out === 0 fires.
      // Also zero out feeRecipientAddress so the
      // feeRecipientNonZero * (feeNoteRecip - feeRecip) constraint passes.
      i.feeNoteRecipientAddress = '0';
      i.outRecipient[2] = '0';
      i.feeRecipientAddress = '0';
      return i;
    },
  },
  {
    name: 'wrong rootLogIndex (accumulator membership fails)',
    mutate: (i) => {
      // Witnessed accumulator path lands at index 0 (slot 0's witness).
      // Mutating to index 5 changes histLeaf and the path bits, so the
      // recomputed accumulator root no longer matches
      // historicalNoteRootAccumulatorRoot.
      i.inRootLogIndex[0] = '5';
      return i;
    },
  },
  {
    name: 'wrong noteRoot (per-input note membership fails)',
    mutate: (i) => {
      // Perturb slot 0's claimed creation-era noteRoot. The Merkle path's
      // computed root no longer equals inNoteRoot[0] for the real input.
      const r0 = BigInt(i.inNoteRoot[0]);
      i.inNoteRoot[0] = ((r0 + 1n) % BigInt('21888242871839275222246405745257275088548364400416034343698204186575808495617')).toString();
      return i;
    },
  },
  {
    name: 'withdrawal-mode witness with outIsReal[1] = 1 (forbidden)',
    mutate: (i) => {
      // Force withdrawal: publicAmountOut > 0 -> operationKind derives to 1.
      // Slot 1 still real -> fails operationKind * outIsReal[1] === 0.
      i.publicAmountOut = '5';
      i.publicTokenAddress = i.tokenAddress;
      i.publicRecipientAddress = i.recipientAddress;
      // Adjust value conservation: 15 inputs - 5 public = 10 outputs.
      // Slot 0 (sender change) 8 + slot 1 5 + slot 2 fee 2 = 15 ≠ 10.
      // Easier: 6 + 2 + 2 = 10. (slot 0 sender change for withdrawal.)
      i.outAmount = ['6', '2', '2'];
      // For the withdrawal binding to land cleanly, slot-0 owner = sender
      i.outRecipient[0] = i.authorizingAddress;
      i.outOwnerNullifierKeyHash[0] = i.outOwnerNullifierKeyHash[1];
      // (don't bother fixing the digest — the slot-1 constraint fires regardless)
      return i;
    },
  },
];

// ---- Run all cases ----
let pass = 0, fail = 0;
for (const c of cases) {
  const inp = c.mutate(clone(BASE));
  const r = tryGenerateWitness(inp);
  if (r.ok) {
    console.log(`FAIL — accepted bad witness: ${c.name}`);
    fail++;
  } else {
    console.log(`OK   — rejected: ${c.name}`);
    pass++;
  }
}

console.log(`\n${pass}/${cases.length} negative cases correctly rejected`);
process.exit(fail === 0 ? 0 : 1);
