// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {Test} from "forge-std/Test.sol";
import {Vm} from "forge-std/Vm.sol";
import {stdJson} from "forge-std/StdJson.sol";
import {ShieldedPool} from "../src/ShieldedPool.sol";
import {InstallSystemContractsBase} from "../script/InstallSystemContracts.s.sol";
import {AuthDemoGroth16Verifier} from "../src/AuthDemoGroth16Verifier.sol";
import {DemoAuthVerifier} from "../src/auth/DemoAuthVerifier.sol";
import {PoseidonFieldLib} from "../src/libraries/PoseidonFieldLib.sol";
import {IAuthVerifier} from "../src/interfaces/IAuthVerifier.sol";
import {ShieldedPoolAcceptAllHarness} from "./ShieldedPoolAcceptAllHarness.sol";
import {ShieldedPoolStepNineHarness} from "./ShieldedPoolStepNineHarness.sol";

/// @notice End-to-end integration of the EIP-8182 reference impl.
///
///         Layer 1 (real-proof): the pool circuit's inline Groth16 verifier
///         (now embedded directly in ShieldedPool) and the auth circuit's
///         IAuthVerifier are exercised against build/integration/session.json
///         (generated by scripts/integration/build_session.js).
///
///         Layer 2 (contract-flow): the `transact` end-to-end path is
///         exercised with the pool-proof check bypassed via
///         ShieldedPoolAcceptAllHarness, confirming the EVM-side state
///         transitions, root histories, and event emissions.
contract IntegrationTest is Test, InstallSystemContractsBase {
    using stdJson for string;

    ShieldedPool internal pool;
    DemoAuthVerifier internal authVerifier;
    AuthDemoGroth16Verifier internal authGroth16;

    string internal session;

    function setUp() public {
        // Install genesis state at SHIELDED_POOL_ADDRESS. After this etch the
        // runtime at POOL_ADDRESS contains the inlined Groth16 verifier.
        install();
        pool = ShieldedPool(POOL_ADDRESS);

        authGroth16 = new AuthDemoGroth16Verifier();
        authVerifier = new DemoAuthVerifier(authGroth16);

        session = vm.readFile("build/integration/session.json");
    }

    // ----------------------- Layer 1: real-proof tests -----------------------

    function testInlinePoolVerifyAcceptsValidProof() public view {
        bytes memory poolProof = vm.parseBytes(stdJson.readString(session, ".pool.proofHex"));
        ShieldedPool.PublicInputs memory pi = _readPublicInputs();

        (uint[2] memory pA, uint[2][2] memory pB, uint[2] memory pC) = _splitProof(poolProof);
        uint[19] memory pub = _packPub(pi);

        bool ok = pool.verifyProof(pA, pB, pC, pub);
        assertTrue(ok, "valid proof must verify");
    }

    function testInlinePoolVerifyRejectsTamperedProof() public view {
        bytes memory poolProof = vm.parseBytes(stdJson.readString(session, ".pool.proofHex"));
        ShieldedPool.PublicInputs memory pi = _readPublicInputs();
        // Flip a bit deep inside C.x (offset 192..223 of the 256-byte proof).
        poolProof[200] = bytes1(uint8(poolProof[200]) ^ 0x01);

        (uint[2] memory pA, uint[2][2] memory pB, uint[2] memory pC) = _splitProof(poolProof);
        uint[19] memory pub = _packPub(pi);

        bool ok = pool.verifyProof(pA, pB, pC, pub);
        assertFalse(ok, "tampered proof must not verify");
    }

    function testInlinePoolVerifyRejectsNoncanonicalPublicInput() public view {
        bytes memory poolProof = vm.parseBytes(stdJson.readString(session, ".pool.proofHex"));
        ShieldedPool.PublicInputs memory pi = _readPublicInputs();
        pi.noteCommitmentRoot = PoseidonFieldLib.FIELD_MODULUS;

        (uint[2] memory pA, uint[2][2] memory pB, uint[2] memory pC) = _splitProof(poolProof);
        uint[19] memory pub = _packPub(pi);

        bool ok = pool.verifyProof(pA, pB, pC, pub);
        assertFalse(ok, "non-canonical input must not verify");
    }

    function testInlinePoolVerifyAcceptsValidProofViaHarness() public {
        vm.etch(POOL_ADDRESS, type(ShieldedPoolStepNineHarness).runtimeCode);
        ShieldedPoolStepNineHarness harness = ShieldedPoolStepNineHarness(POOL_ADDRESS);
        bytes memory poolProof = vm.parseBytes(stdJson.readString(session, ".pool.proofHex"));
        ShieldedPool.PublicInputs memory pi = _readPublicInputs();
        harness.exposeVerifyPoolProof(poolProof, pi);
    }

    function testInlinePoolVerifyRejectsMalformedProofEncoding() public {
        vm.etch(POOL_ADDRESS, type(ShieldedPoolStepNineHarness).runtimeCode);
        ShieldedPoolStepNineHarness harness = ShieldedPoolStepNineHarness(POOL_ADDRESS);
        ShieldedPool.PublicInputs memory pi = _readPublicInputs();
        vm.expectRevert(ShieldedPool.PoolProofRejected.selector);
        harness.exposeVerifyPoolProof(new bytes(255), pi);
    }

    function testInlinePoolVerifyRejectsNoncanonicalNullifier() public {
        bytes memory poolProof = vm.parseBytes(stdJson.readString(session, ".pool.proofHex"));
        ShieldedPool.PublicInputs memory pi = _readPublicInputs();
        pi.nullifier0 = PoseidonFieldLib.FIELD_MODULUS;

        vm.etch(POOL_ADDRESS, type(ShieldedPoolStepNineHarness).runtimeCode);
        ShieldedPoolStepNineHarness harness = ShieldedPoolStepNineHarness(POOL_ADDRESS);
        vm.expectRevert(ShieldedPool.PoolProofRejected.selector);
        harness.exposeVerifyPoolProof(poolProof, pi);
    }

    function testAuthVerifierAcceptsValidProof() public view {
        bytes memory authProof = vm.parseBytes(stdJson.readString(session, ".auth.proofHex"));
        ShieldedPool.PublicInputs memory pi = _readPublicInputs();

        bool ok = authVerifier.verifyAuth(
            abi.encode(pi.blindedAuthCommitment, pi.transactionIntentDigest),
            authProof
        );
        assertTrue(ok, "auth proof must verify");
    }

    function testAuthVerifierRejectsWrongPublicInputs() public view {
        bytes memory authProof = vm.parseBytes(stdJson.readString(session, ".auth.proofHex"));
        ShieldedPool.PublicInputs memory pi = _readPublicInputs();

        bool ok = authVerifier.verifyAuth(
            abi.encode(pi.blindedAuthCommitment + 1, pi.transactionIntentDigest),
            authProof
        );
        assertFalse(ok, "auth verifier must reject wrong public inputs");
    }

    // --------------------- Layer 2: contract-flow tests ----------------------

    function testTransactWithMockVerifiersUpdatesAllRoots() public {
        AcceptAllAuthVerifier alwaysAcceptAuth = new AcceptAllAuthVerifier();
        vm.etch(POOL_ADDRESS, type(ShieldedPoolAcceptAllHarness).runtimeCode);

        // Register a sender so transact's pre-checks all hold.
        address sender = address(0x1234);
        uint256 senderOnk = uint256(keccak256("sender owner nullifier key hash")) % PoseidonFieldLib.FIELD_MODULUS;
        uint256 senderSeed = uint256(keccak256("sender note secret seed hash")) % PoseidonFieldLib.FIELD_MODULUS;
        uint256 policySet = uint256(keccak256("policy set commitment")) % PoseidonFieldLib.FIELD_MODULUS;
        vm.prank(sender);
        pool.setAuthPolicy(senderOnk, senderSeed, policySet);

        (uint256 noteRootBefore, uint256 authPolicyRootBefore) = pool.getCurrentRoots();

        ShieldedPool.PublicInputs memory pi = ShieldedPool.PublicInputs({
            noteCommitmentRoot: noteRootBefore,
            nullifier0: 0x111,
            nullifier1: 0x222,
            noteBodyCommitment0: 0xb1,
            noteBodyCommitment1: 0xb2,
            noteBodyCommitment2: 0xb3,
            publicAmountOut: 0,
            publicRecipientAddress: 0,
            publicTokenAddress: 0,
            intentReplayId: 0xdeadbeef,
            validUntilSeconds: uint256(block.timestamp + 600),
            executionChainId: block.chainid,
            authPolicyRoot: authPolicyRootBefore,
            outputNoteDataHash0: uint256(keccak256("o0")) % PoseidonFieldLib.FIELD_MODULUS,
            outputNoteDataHash1: uint256(keccak256("o1")) % PoseidonFieldLib.FIELD_MODULUS,
            outputNoteDataHash2: uint256(keccak256("o2")) % PoseidonFieldLib.FIELD_MODULUS,
            authVerifier: uint256(uint160(address(alwaysAcceptAuth))),
            blindedAuthCommitment: 0xc0ffee,
            transactionIntentDigest: 0xb16b00b5
        });

        bytes memory dummyProof = new bytes(256);
        bytes memory dummyAuth = new bytes(256);
        pool.transact(dummyProof, dummyAuth, pi, "o0", "o1", "o2");

        (uint256 noteRootAfter,) = pool.getCurrentRoots();
        assertTrue(noteRootAfter != noteRootBefore, "note tree must advance after transact");
        assertTrue(pool.isNullifierSpent(0x111));
        assertTrue(pool.isNullifierSpent(0x222));
        assertTrue(pool.isIntentReplayIdUsed(0xdeadbeef));
    }

    function testSetAuthPolicyFirstCallAssignsLeafPositionOne() public {
        address user = address(0xABCD);
        vm.prank(user);
        uint256 leafPos = pool.setAuthPolicy(123, 456, 789);
        assertEq(leafPos, 1, "first setAuthPolicy from any address gets slot 1");

        (bool reg, ShieldedPool.UserEntry memory entry) = pool.getAuthPolicyEntry(user);
        assertTrue(reg);
        assertEq(entry.leafPosition, 1);
        assertEq(entry.ownerNullifierKeyHash, 123);
        assertEq(entry.noteSecretSeedHash, 456);
        assertEq(entry.policySetCommitment, 789);
    }

    function testSetAuthPolicySecondAddressGetsSlotTwo() public {
        vm.prank(address(0xAA));
        uint256 first = pool.setAuthPolicy(0xa1, 0xa2, 0xa3);
        vm.prank(address(0xBB));
        uint256 second = pool.setAuthPolicy(0xb1, 0xb2, 0xb3);
        assertEq(first, 1);
        assertEq(second, 2);
    }

    function testSetAuthPolicyAllowsRotationOfSeedAndPolicySet() public {
        address user = address(0xABCD);
        vm.prank(user);
        pool.setAuthPolicy(0xa1, 0xa2, 0xa3);
        vm.prank(user);
        pool.setAuthPolicy(0xa1, 0xb2, 0xb3); // same onkHash, rotated seed + policy set

        (, ShieldedPool.UserEntry memory entry) = pool.getAuthPolicyEntry(user);
        assertEq(entry.ownerNullifierKeyHash, 0xa1, "ownerNullifierKeyHash must be unchanged");
        assertEq(entry.noteSecretSeedHash, 0xb2, "noteSecretSeedHash rotated");
        assertEq(entry.policySetCommitment, 0xb3, "policySetCommitment rotated");
    }

    function testSetAuthPolicyRevertsOnOwnerNullifierKeyHashImmutable() public {
        address user = address(0xABCD);
        vm.prank(user);
        pool.setAuthPolicy(0xa1, 0xa2, 0xa3);
        vm.prank(user);
        vm.expectRevert(ShieldedPool.OwnerNullifierKeyHashImmutable.selector);
        pool.setAuthPolicy(0xa9, 0xa2, 0xa3); // different onkHash on second call
    }

    function testSetAuthPolicyRevertsOnDuplicateOwnerNullifierKeyHash() public {
        address userA = address(0xA1);
        address userB = address(0xB2);
        uint256 dup = 0xCAFE;
        vm.prank(userA);
        pool.setAuthPolicy(dup, 0x1234, 0x5678);
        vm.prank(userB);
        vm.expectRevert(ShieldedPool.OwnerNullifierKeyHashAlreadyUsed.selector);
        pool.setAuthPolicy(dup, 0x9abc, 0xdef0);
    }

    function testSetAuthPolicyRevertsOnReservedZeroOwnerNullifierKeyHash() public {
        vm.expectRevert(ShieldedPool.ReservedOwnerNullifierKeyHash.selector);
        pool.setAuthPolicy(0, 0x1234, 0x5678);
    }

    function testSetAuthPolicyRevertsOnReservedDummyOwnerNullifierKeyHash() public {
        uint256 dummy = PoseidonFieldLib.dummyOwnerNullifierKeyHash();
        vm.expectRevert(ShieldedPool.ReservedOwnerNullifierKeyHash.selector);
        pool.setAuthPolicy(dummy, 0x1234, 0x5678);
    }

    function testSetAuthPolicyRevertsOnZeroNoteSecretSeedHash() public {
        vm.expectRevert(ShieldedPool.ZeroNoteSecretSeedHash.selector);
        pool.setAuthPolicy(0x1234, 0, 0x5678);
    }

    function testSetAuthPolicyRevertsOnNonCanonicalOwnerNullifierKeyHash() public {
        vm.expectRevert(ShieldedPool.FieldElementNotCanonical.selector);
        pool.setAuthPolicy(PoseidonFieldLib.FIELD_MODULUS, 0x1234, 0x5678);
    }

    function testSetAuthPolicyRevertsOnNonCanonicalPolicySetCommitment() public {
        vm.expectRevert(ShieldedPool.FieldElementNotCanonical.selector);
        pool.setAuthPolicy(0x1234, 0x5678, PoseidonFieldLib.FIELD_MODULUS);
    }

    function testGetAuthPolicyEntryReturnsZeroForUnregistered() public view {
        // Section 5.3 normative: for an unregistered address `entry` MUST be
        // the zero-valued UserEntry and `registered` MUST be false.
        (bool registered, ShieldedPool.UserEntry memory entry) =
            pool.getAuthPolicyEntry(address(0xFEED));
        assertFalse(registered, "unregistered address must report registered=false");
        assertEq(entry.leafPosition, 0, "leafPosition must be zero for unregistered");
        assertEq(entry.ownerNullifierKeyHash, 0, "ownerNullifierKeyHash must be zero for unregistered");
        assertEq(entry.noteSecretSeedHash, 0, "noteSecretSeedHash must be zero for unregistered");
        assertEq(entry.policySetCommitment, 0, "policySetCommitment must be zero for unregistered");
    }

    function testSetAuthPolicyRevertsTreeFull() public {
        // nextLeafPosition is storage slot 5 (verified via `forge inspect
        // ShieldedPool storage-layout`). The `require(newPosition <=
        // MAX_LEAF_INDEX, TreeFull)` gate in setAuthPolicy must reject the
        // first value > 2^32 - 1.
        vm.store(POOL_ADDRESS, bytes32(uint256(5)), bytes32(uint256(1) << 32));

        vm.prank(address(0xC0DE));
        vm.expectRevert(ShieldedPool.TreeFull.selector);
        pool.setAuthPolicy(0xa1, 0xa2, 0xa3);
    }

    function testDepositAdvancesNoteCommitmentRoot() public {
        (uint256 before,) = pool.getCurrentRoots();
        uint256 ownerCommitment = uint256(keccak256("owner commitment")) % PoseidonFieldLib.FIELD_MODULUS;
        vm.deal(address(this), 1 ether);
        pool.deposit{value: 1 ether}(address(0), 1 ether, ownerCommitment, "delivery payload");
        (uint256 afterRoot,) = pool.getCurrentRoots();
        assertTrue(afterRoot != before, "deposit must advance note tree");
        assertEq(address(pool).balance, 1 ether);
    }

    // ----------------------- Layer 2: negative tests -------------------------

    function _setupForTransact()
        internal
        returns (
            ShieldedPool.PublicInputs memory pi,
            AcceptAllAuthVerifier acceptAuth
        )
    {
        vm.etch(POOL_ADDRESS, type(ShieldedPoolAcceptAllHarness).runtimeCode);
        acceptAuth = new AcceptAllAuthVerifier();

        address sender = address(0x1234);
        uint256 senderOnk = uint256(keccak256("sender onk")) % PoseidonFieldLib.FIELD_MODULUS;
        uint256 senderSeed = uint256(keccak256("sender seed")) % PoseidonFieldLib.FIELD_MODULUS;
        uint256 policySet = uint256(keccak256("sender policy set")) % PoseidonFieldLib.FIELD_MODULUS;
        vm.prank(sender);
        pool.setAuthPolicy(senderOnk, senderSeed, policySet);

        pi = _basePI(address(acceptAuth));
    }

    function _basePI(address authVerifierAddr)
        internal
        view
        returns (ShieldedPool.PublicInputs memory pi)
    {
        (uint256 noteRoot, uint256 authPolicyRoot) = pool.getCurrentRoots();
        pi = ShieldedPool.PublicInputs({
            noteCommitmentRoot: noteRoot,
            nullifier0: 0x111,
            nullifier1: 0x222,
            noteBodyCommitment0: 0xb1,
            noteBodyCommitment1: 0xb2,
            noteBodyCommitment2: 0xb3,
            publicAmountOut: 0,
            publicRecipientAddress: 0,
            publicTokenAddress: 0,
            intentReplayId: 0xdeadbeef,
            validUntilSeconds: uint256(block.timestamp + 600),
            executionChainId: block.chainid,
            authPolicyRoot: authPolicyRoot,
            outputNoteDataHash0: uint256(keccak256("o0")) % PoseidonFieldLib.FIELD_MODULUS,
            outputNoteDataHash1: uint256(keccak256("o1")) % PoseidonFieldLib.FIELD_MODULUS,
            outputNoteDataHash2: uint256(keccak256("o2")) % PoseidonFieldLib.FIELD_MODULUS,
            authVerifier: uint256(uint160(authVerifierAddr)),
            blindedAuthCommitment: 0xc0ffee,
            transactionIntentDigest: 0xb16b00b5
        });
    }

    function testTransactRevertsWhenAuthVerifierHasNoCode() public {
        address noCodeVerifier = address(0xC0dE0000c0De0000C0DE0000c0De0000c0DE0000);
        (ShieldedPool.PublicInputs memory pi, ) = _setupForTransact();
        pi.authVerifier = uint256(uint160(noCodeVerifier));

        vm.expectRevert(ShieldedPool.AuthVerifierMissing.selector);
        pool.transact(new bytes(256), new bytes(256), pi, "o0", "o1", "o2");
    }

    function testTransactRevertsAmountOutOfRange() public {
        (ShieldedPool.PublicInputs memory pi, ) = _setupForTransact();
        pi.publicAmountOut = uint256(1) << 248;

        vm.expectRevert(ShieldedPool.AmountOutOfRange.selector);
        pool.transact(new bytes(256), new bytes(256), pi, "o0", "o1", "o2");
    }

    function testTransactRevertsAddressOutOfRangeRecipient() public {
        (ShieldedPool.PublicInputs memory pi, ) = _setupForTransact();
        pi.publicRecipientAddress = uint256(1) << 160;

        vm.expectRevert(ShieldedPool.AddressOutOfRange.selector);
        pool.transact(new bytes(256), new bytes(256), pi, "o0", "o1", "o2");
    }

    function testTransactRevertsAddressOutOfRangeToken() public {
        (ShieldedPool.PublicInputs memory pi, ) = _setupForTransact();
        pi.publicTokenAddress = uint256(1) << 160;

        vm.expectRevert(ShieldedPool.AddressOutOfRange.selector);
        pool.transact(new bytes(256), new bytes(256), pi, "o0", "o1", "o2");
    }

    function testTransactRevertsAddressOutOfRangeAuthVerifier() public {
        (ShieldedPool.PublicInputs memory pi, ) = _setupForTransact();
        pi.authVerifier = uint256(1) << 160;

        vm.expectRevert(ShieldedPool.AddressOutOfRange.selector);
        pool.transact(new bytes(256), new bytes(256), pi, "o0", "o1", "o2");
    }

    function testTransactRevertsAuthVerifierZero() public {
        (ShieldedPool.PublicInputs memory pi, ) = _setupForTransact();
        pi.authVerifier = 0;

        vm.expectRevert(ShieldedPool.AuthVerifierMissing.selector);
        pool.transact(new bytes(256), new bytes(256), pi, "o0", "o1", "o2");
    }

    function testTransactRevertsIntentExpiredZero() public {
        (ShieldedPool.PublicInputs memory pi, ) = _setupForTransact();
        pi.validUntilSeconds = 0;

        vm.expectRevert(ShieldedPool.IntentExpired.selector);
        pool.transact(new bytes(256), new bytes(256), pi, "o0", "o1", "o2");
    }

    function testTransactRevertsIntentExpiredPast() public {
        vm.warp(1000);
        (ShieldedPool.PublicInputs memory pi, ) = _setupForTransact();
        pi.validUntilSeconds = block.timestamp - 1;

        vm.expectRevert(ShieldedPool.IntentExpired.selector);
        pool.transact(new bytes(256), new bytes(256), pi, "o0", "o1", "o2");
    }

    function testTransactRevertsIntentExpiredAtUint32Boundary() public {
        (ShieldedPool.PublicInputs memory pi, ) = _setupForTransact();
        pi.validUntilSeconds = uint256(1) << 32;

        vm.expectRevert(ShieldedPool.IntentExpired.selector);
        pool.transact(new bytes(256), new bytes(256), pi, "o0", "o1", "o2");
    }

    function testTransactRevertsIntentLifetimeTooLong() public {
        vm.warp(1000);
        (ShieldedPool.PublicInputs memory pi, ) = _setupForTransact();
        pi.validUntilSeconds = block.timestamp + 86400 + 1;

        vm.expectRevert(ShieldedPool.IntentLifetimeTooLong.selector);
        pool.transact(new bytes(256), new bytes(256), pi, "o0", "o1", "o2");
    }

    function testTransactRevertsWrongChainId() public {
        (ShieldedPool.PublicInputs memory pi, ) = _setupForTransact();
        pi.executionChainId = block.chainid + 1;

        vm.expectRevert(ShieldedPool.WrongChainId.selector);
        pool.transact(new bytes(256), new bytes(256), pi, "o0", "o1", "o2");
    }

    function testTransactRevertsDuplicateNullifier() public {
        (ShieldedPool.PublicInputs memory pi, ) = _setupForTransact();
        pi.nullifier1 = pi.nullifier0;

        vm.expectRevert(ShieldedPool.DuplicateNullifier.selector);
        pool.transact(new bytes(256), new bytes(256), pi, "o0", "o1", "o2");
    }

    function testTransactRevertsIntentReplayIdAlreadyUsed() public {
        (ShieldedPool.PublicInputs memory pi, ) = _setupForTransact();
        pool.transact(new bytes(256), new bytes(256), pi, "o0", "o1", "o2");

        pi.nullifier0 = 0x333;
        pi.nullifier1 = 0x444;

        vm.expectRevert(ShieldedPool.IntentReplayIdAlreadyUsed.selector);
        pool.transact(new bytes(256), new bytes(256), pi, "o0", "o1", "o2");
    }

    function testTransactRevertsInvalidOutputNoteDataHash() public {
        (ShieldedPool.PublicInputs memory pi, ) = _setupForTransact();
        vm.expectRevert(
            abi.encodeWithSelector(ShieldedPool.InvalidOutputNoteDataHash.selector, uint8(0))
        );
        pool.transact(new bytes(256), new bytes(256), pi, "OOPS", "o1", "o2");
    }

    function testTransactRevertsUnknownNoteCommitmentRoot() public {
        (ShieldedPool.PublicInputs memory pi, ) = _setupForTransact();
        pi.noteCommitmentRoot = uint256(keccak256("not in history"))
            % PoseidonFieldLib.FIELD_MODULUS;

        vm.expectRevert(ShieldedPool.UnknownNoteCommitmentRoot.selector);
        pool.transact(new bytes(256), new bytes(256), pi, "o0", "o1", "o2");
    }

    function testTransactAcceptsHistoricalNoteCommitmentRoot() public {
        // Section 3.5 requires the verifier to accept any noteCommitmentRoot
        // from the last NOTE_COMMITMENT_ROOT_HISTORY_SIZE (= 500) roots, not
        // just the current tip.
        (ShieldedPool.PublicInputs memory pi, ) = _setupForTransact();
        uint256 historicalNoteRoot = pi.noteCommitmentRoot;
        pool.transact(new bytes(256), new bytes(256), pi, "o0", "o1", "o2");

        (uint256 noteRootAfter,) = pool.getCurrentRoots();
        assertTrue(noteRootAfter != historicalNoteRoot, "first transact must advance note tree");

        // Second transact reuses the pre-first-transact root. Fresh nullifiers
        // / intentReplayId / outputs avoid collisions with the first call.
        pi.noteCommitmentRoot = historicalNoteRoot;
        pi.nullifier0 = 0x333;
        pi.nullifier1 = 0x444;
        pi.intentReplayId = 0xfeedface;
        pi.outputNoteDataHash0 = uint256(keccak256("h0")) % PoseidonFieldLib.FIELD_MODULUS;
        pi.outputNoteDataHash1 = uint256(keccak256("h1")) % PoseidonFieldLib.FIELD_MODULUS;
        pi.outputNoteDataHash2 = uint256(keccak256("h2")) % PoseidonFieldLib.FIELD_MODULUS;
        pool.transact(new bytes(256), new bytes(256), pi, "h0", "h1", "h2");
    }

    function testTransactRevertsOnEvictedNoteCommitmentRoot() public {
        // Section 3.5: the note-root history is a 500-entry ring buffer; once
        // a root has been overwritten by NOTE_COMMITMENT_ROOT_HISTORY_SIZE (=
        // 500) subsequent pushes it is no longer accepted. The transact path
        // must surface that with UnknownNoteCommitmentRoot.
        (uint256 genesisRoot,) = pool.getCurrentRoots();
        uint256 ownerCommitment = uint256(keccak256("evict-oc")) % PoseidonFieldLib.FIELD_MODULUS;
        vm.deal(address(this), 1 ether);

        // First deposit pushes genesisRoot into slot 0 (count becomes 1).
        pool.deposit{value: 1 wei}(address(0), 1, ownerCommitment, "");

        // Bookkeeping skip-ahead: bump noteCommitmentRootHistoryCount to 500
        // so the next push lands at slot 500 % 500 = 0, overwriting genesis.
        // Slot 2 verified via `forge inspect ShieldedPool storage-layout`.
        vm.store(POOL_ADDRESS, bytes32(uint256(2)), bytes32(uint256(500)));

        // Second deposit triggers the wraparound at slot 0.
        pool.deposit{value: 1 wei}(address(0), 1, ownerCommitment + 1, "");

        assertFalse(
            pool.isAcceptedNoteCommitmentRoot(genesisRoot),
            "post-wraparound: genesis root must no longer be accepted"
        );

        (ShieldedPool.PublicInputs memory pi, ) = _setupForTransact();
        pi.noteCommitmentRoot = genesisRoot;
        vm.expectRevert(ShieldedPool.UnknownNoteCommitmentRoot.selector);
        pool.transact(new bytes(256), new bytes(256), pi, "o0", "o1", "o2");
    }

    function testTransactRevertsZeroAuthPolicyRoot() public {
        (ShieldedPool.PublicInputs memory pi, ) = _setupForTransact();
        pi.authPolicyRoot = 0;

        vm.expectRevert(ShieldedPool.ZeroAuthPolicyRoot.selector);
        pool.transact(new bytes(256), new bytes(256), pi, "o0", "o1", "o2");
    }

    function testTransactRevertsUnknownAuthPolicyRoot() public {
        (ShieldedPool.PublicInputs memory pi, ) = _setupForTransact();
        pi.authPolicyRoot = uint256(keccak256("not in history"))
            % PoseidonFieldLib.FIELD_MODULUS;

        vm.expectRevert(ShieldedPool.UnknownAuthPolicyRoot.selector);
        pool.transact(new bytes(256), new bytes(256), pi, "o0", "o1", "o2");
    }

    function testTransactRevertsOnExpiredAuthPolicyRoot() public {
        // Section 3.6 / Section 5.4.1: roots fall out of the verifier's
        // accepted set once `block.number - snapshotBlock` exceeds
        // AUTH_POLICY_ROOT_HISTORY_BLOCKS (= 64).
        (ShieldedPool.PublicInputs memory pi, ) = _setupForTransact();
        uint256 expiringRoot = pi.authPolicyRoot;

        // Bump the current root via a second setAuthPolicy in a later block,
        // so `expiringRoot` is no longer the current root and gets a fresh
        // snapshot entry attached to this newer block.
        vm.roll(block.number + 1);
        vm.prank(address(0xDEAD));
        pool.setAuthPolicy(0xbeef, 0xface, 0xcafe);
        (, uint256 newRoot) = pool.getCurrentRoots();
        assertTrue(newRoot != expiringRoot, "second setAuthPolicy must advance authPolicyRoot");

        // Advance past the 64-block freshness window. AUTH_POLICY_ROOT_HISTORY_BLOCKS
        // is internal, so hard-code the matching constant here.
        vm.roll(block.number + 65);

        pi.authPolicyRoot = expiringRoot;
        vm.expectRevert(ShieldedPool.UnknownAuthPolicyRoot.selector);
        pool.transact(new bytes(256), new bytes(256), pi, "o0", "o1", "o2");
    }

    function testTransactAcceptsHistoricalAuthPolicyRootInWindow() public {
        // Section 3.6: an authPolicyRoot that's no longer current must still
        // be accepted by transact if it was snapshotted within the last
        // AUTH_POLICY_ROOT_HISTORY_BLOCKS (= 64) blocks.
        (ShieldedPool.PublicInputs memory pi, ) = _setupForTransact();
        uint256 olderRoot = pi.authPolicyRoot;

        // Bump current root via a second setAuthPolicy in a later block; the
        // older root is now in history attached to that later block number.
        vm.roll(block.number + 1);
        vm.prank(address(0xDEAD));
        pool.setAuthPolicy(0xbeef, 0xface, 0xcafe);
        (, uint256 newRoot) = pool.getCurrentRoots();
        assertTrue(newRoot != olderRoot, "second setAuthPolicy must advance authPolicyRoot");

        // Stay within the 64-block freshness window.
        vm.roll(block.number + 10);

        assertTrue(
            pool.isAcceptedAuthPolicyRoot(olderRoot),
            "10-block-old root must remain accepted"
        );

        // End-to-end: transact must succeed with the in-window historical root.
        pi.authPolicyRoot = olderRoot;
        pool.transact(new bytes(256), new bytes(256), pi, "o0", "o1", "o2");
    }

    function testDepositRevertsOnEthAmountMismatch() public {
        uint256 ownerCommitment = uint256(keccak256("oc")) % PoseidonFieldLib.FIELD_MODULUS;
        vm.deal(address(this), 2 ether);
        vm.expectRevert(ShieldedPool.EthAmountMismatch.selector);
        pool.deposit{value: 0.5 ether}(address(0), 1 ether, ownerCommitment, "delivery");
    }

    function testDepositRevertsOnZeroAmount() public {
        uint256 ownerCommitment = uint256(keccak256("oc")) % PoseidonFieldLib.FIELD_MODULUS;
        vm.expectRevert(ShieldedPool.InvalidDepositAmount.selector);
        pool.deposit(address(0), 0, ownerCommitment, "delivery");
    }

    function testTransactRevertsOnAuthVerifierShortReturn() public {
        BadReturnAuthVerifier badVerifier = new BadReturnAuthVerifier();
        (ShieldedPool.PublicInputs memory pi, ) = _setupForTransact();
        pi.authVerifier = uint256(uint160(address(badVerifier)));

        vm.expectRevert(ShieldedPool.AuthProofRejected.selector);
        pool.transact(new bytes(256), new bytes(256), pi, "o0", "o1", "o2");
    }

    function testTransactRevertsOnAuthVerifierReturningFalse() public {
        RejectAllAuthVerifier rejectVerifier = new RejectAllAuthVerifier();
        (ShieldedPool.PublicInputs memory pi, ) = _setupForTransact();
        pi.authVerifier = uint256(uint160(address(rejectVerifier)));

        vm.expectRevert(ShieldedPool.AuthProofRejected.selector);
        pool.transact(new bytes(256), new bytes(256), pi, "o0", "o1", "o2");
    }

    function testTransactRevertsOnAuthVerifierStaticcallRevert() public {
        // Section 5.4.1 step 8: a staticcall failure on the auth verifier must
        // be treated as AuthProofRejected, not propagated as a generic revert.
        RevertingAuthVerifier reverter = new RevertingAuthVerifier();
        (ShieldedPool.PublicInputs memory pi, ) = _setupForTransact();
        pi.authVerifier = uint256(uint160(address(reverter)));

        vm.expectRevert(ShieldedPool.AuthProofRejected.selector);
        pool.transact(new bytes(256), new bytes(256), pi, "o0", "o1", "o2");
    }

    // ----------------------------- Helpers -----------------------------------

    function _splitProof(bytes memory proof)
        private
        pure
        returns (uint[2] memory pA, uint[2][2] memory pB, uint[2] memory pC)
    {
        require(proof.length == 256, "proof must be 256 bytes");
        pA = [_w(proof, 0), _w(proof, 32)];
        pB = [
            [_w(proof, 64),  _w(proof, 96)],
            [_w(proof, 128), _w(proof, 160)]
        ];
        pC = [_w(proof, 192), _w(proof, 224)];
    }

    function _packPub(ShieldedPool.PublicInputs memory pi)
        private
        pure
        returns (uint[19] memory pub)
    {
        pub[0]  = pi.noteCommitmentRoot;
        pub[1]  = pi.nullifier0;
        pub[2]  = pi.nullifier1;
        pub[3]  = pi.noteBodyCommitment0;
        pub[4]  = pi.noteBodyCommitment1;
        pub[5]  = pi.noteBodyCommitment2;
        pub[6]  = pi.publicAmountOut;
        pub[7]  = pi.publicRecipientAddress;
        pub[8]  = pi.publicTokenAddress;
        pub[9]  = pi.intentReplayId;
        pub[10] = pi.validUntilSeconds;
        pub[11] = pi.executionChainId;
        pub[12] = pi.authPolicyRoot;
        pub[13] = pi.outputNoteDataHash0;
        pub[14] = pi.outputNoteDataHash1;
        pub[15] = pi.outputNoteDataHash2;
        pub[16] = pi.authVerifier;
        pub[17] = pi.blindedAuthCommitment;
        pub[18] = pi.transactionIntentDigest;
    }

    function _w(bytes memory src, uint256 offset) private pure returns (uint256 r) {
        assembly { r := mload(add(add(src, 32), offset)) }
    }

    function _readPublicInputs() private view returns (ShieldedPool.PublicInputs memory pi) {
        uint256[] memory ps = new uint256[](19);
        for (uint256 i; i < 19; ++i) {
            ps[i] = stdJson.readUint(
                session, string.concat(".pool.publicSignals[", vm.toString(i), "]")
            );
        }
        pi.noteCommitmentRoot = ps[0];
        pi.nullifier0 = ps[1];
        pi.nullifier1 = ps[2];
        pi.noteBodyCommitment0 = ps[3];
        pi.noteBodyCommitment1 = ps[4];
        pi.noteBodyCommitment2 = ps[5];
        pi.publicAmountOut = ps[6];
        pi.publicRecipientAddress = ps[7];
        pi.publicTokenAddress = ps[8];
        pi.intentReplayId = ps[9];
        pi.validUntilSeconds = ps[10];
        pi.executionChainId = ps[11];
        pi.authPolicyRoot = ps[12];
        pi.outputNoteDataHash0 = ps[13];
        pi.outputNoteDataHash1 = ps[14];
        pi.outputNoteDataHash2 = ps[15];
        pi.authVerifier = ps[16];
        pi.blindedAuthCommitment = ps[17];
        pi.transactionIntentDigest = ps[18];
    }
}

/// @notice Always-accept auth verifier for contract-flow tests.
contract AcceptAllAuthVerifier is IAuthVerifier {
    function verifyAuth(bytes calldata, bytes calldata) external pure override returns (bool) {
        return true;
    }
}

/// @notice Auth verifier that returns `false`. Used to confirm `transact`
///         maps a negative auth result to `AuthProofRejected`.
contract RejectAllAuthVerifier is IAuthVerifier {
    function verifyAuth(bytes calldata, bytes calldata) external pure override returns (bool) {
        return false;
    }
}

/// @notice Auth verifier whose `verifyAuth` returns exactly 16 bytes via raw
///         RETURN, breaking the IAuthVerifier ABI shape.
///         `_verifyAuthProof` MUST reject any non-32-byte return.
contract BadReturnAuthVerifier {
    function verifyAuth(bytes calldata, bytes calldata) external pure returns (bool) {
        assembly {
            mstore(0x00, 0x0000000000000000000000000000000100000000000000000000000000000000)
            return(0x00, 16)
        }
    }
}

/// @notice Auth verifier whose `verifyAuth` reverts. The pool's staticcall
///         must surface this as `AuthProofRejected` rather than propagating
///         the raw revert.
contract RevertingAuthVerifier is IAuthVerifier {
    function verifyAuth(bytes calldata, bytes calldata) external pure override returns (bool) {
        revert();
    }
}
