[package]
name = "auth"
type = "bin"
authors = [""]
compiler_version = ">=1.0.0"

[dependencies]
privacy_pool_common = { path = "../common" }
keccak256 = { path = "../vendor/keccak256" }
poseidon = { path = "../vendor/poseidon" }
