// Emits circuits-noir/auth/src/vector_test.nr from assets/derivation_vectors.json.
// The test runs the full auth relation (EIP-712 hash -> ECDSA verify -> digest)
// on the transfer scenario's real signature and pins both public outputs.
// If the TS hashTypedData and the Noir eip712_signing_hash ever disagree, the
// signature check fails and this test catches it.
//
// Run: node scripts/gen_noir_vector_test.js   (after gen_vectors.ts)

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ERC = path.resolve(HERE, "..");
const V = JSON.parse(fs.readFileSync(path.join(ERC, "assets/derivation_vectors.json"), "utf8"));
const s = V.scenarios.transfer;
const f = s.intentFields;

const bytes32 = (hexStr, name) => {
  const clean = hexStr.replace(/^0x/, "").padStart(64, "0");
  if (clean.length !== 64) throw new Error(`${name} not 32 bytes`);
  const rows = [];
  for (let i = 0; i < 64; i += 16) {
    rows.push(
      "        " +
        Array.from({ length: 8 }, (_, j) => "0x" + clean.slice(i + j * 2, i + j * 2 + 2)).join(", ") +
        ",",
    );
  }
  return rows.join("\n");
};

const sigHex = (s.eip712.r.replace(/^0x/, "").padStart(64, "0")) + (s.eip712.s.replace(/^0x/, "").padStart(64, "0"));
const sigRows = [];
for (let i = 0; i < 128; i += 16) {
  sigRows.push(
    "        " +
      Array.from({ length: 8 }, (_, j) => "0x" + sigHex.slice(i + j * 2, i + j * 2 + 2)).join(", ") +
      ",",
  );
}

const out = `// Auto-generated by erc/scripts/gen_noir_vector_test.js - do not edit.
// Pins the auth relation to the transfer scenario in derivation_vectors.json.

#[test]
fn test_vector_transfer_full_relation() {
    let nonce: [u8; 32] = [
${bytes32(s.nonce, "nonce")}
    ];
    let pubkey_x: [u8; 32] = [
${bytes32(s.eip712.publicKeyX, "pubkey_x")}
    ];
    let pubkey_y: [u8; 32] = [
${bytes32(s.eip712.publicKeyY, "pubkey_y")}
    ];
    let signature: [u8; 64] = [
${sigRows.join("\n")}
    ];

    let (blinded, digest) = crate::main(
        ${BigInt(f.executionChainId)}, // execution_chain_id
        ${BigInt(f.poolAddress)}, // pool_address
        ${BigInt(f.authVerifier)}, // auth_verifier
        ${BigInt(f.authorizingAddress)}, // authorizing_address
        ${BigInt(f.operationKind)}, // operation_kind
        ${BigInt(f.tokenAddress)}, // token_address
        ${BigInt(f.recipientOwnerNullifierKeyHash)}, // recipient_owner_nullifier_key_hash
        ${BigInt(f.amount)}, // amount
        ${BigInt(f.feeNoteRecipientOwnerNullifierKeyHash)}, // fee_note_recipient_owner_nullifier_key_hash
        ${BigInt(f.feeAmount)}, // fee_amount
        ${BigInt(f.publicRecipientAddress)}, // public_recipient_address
        ${BigInt(f.authorizedSubmitter)}, // authorized_submitter
        ${BigInt(f.downstreamActionCommitment)}, // downstream_action_commitment
        ${BigInt(f.executionConstraintsFlags)}, // execution_constraints_flags
        ${BigInt(f.lockedOutputBinding0)}, // locked_output_binding0
        ${BigInt(f.lockedOutputBinding1)}, // locked_output_binding1
        ${BigInt(f.lockedOutputBinding2)}, // locked_output_binding2
        ${BigInt(s.policyDataHash)}, // policy_data_hash
        nonce,
        ${BigInt(f.validUntilSeconds)}, // valid_until_seconds
        pubkey_x,
        pubkey_y,
        signature,
        ${BigInt(s.blindingFactor)}, // blinding_factor
    );

    assert(blinded == ${BigInt(s.blindedAuthCommitment)});
    assert(digest == ${BigInt(s.transactionIntentDigest)});
}

#[test(should_fail)]
fn test_vector_transfer_wrong_pool_address_fails() {
    let nonce: [u8; 32] = [
${bytes32(s.nonce, "nonce")}
    ];
    let pubkey_x: [u8; 32] = [
${bytes32(s.eip712.publicKeyX, "pubkey_x")}
    ];
    let pubkey_y: [u8; 32] = [
${bytes32(s.eip712.publicKeyY, "pubkey_y")}
    ];
    let signature: [u8; 64] = [
${sigRows.join("\n")}
    ];

    // Different pool identity -> different EIP-712 digest -> signature invalid.
    let (_b, _d) = crate::main(
        ${BigInt(f.executionChainId)},
        ${BigInt(f.poolAddress) + 1n}, // WRONG pool_address
        ${BigInt(f.authVerifier)},
        ${BigInt(f.authorizingAddress)},
        ${BigInt(f.operationKind)},
        ${BigInt(f.tokenAddress)},
        ${BigInt(f.recipientOwnerNullifierKeyHash)},
        ${BigInt(f.amount)},
        ${BigInt(f.feeNoteRecipientOwnerNullifierKeyHash)},
        ${BigInt(f.feeAmount)},
        ${BigInt(f.publicRecipientAddress)},
        ${BigInt(f.authorizedSubmitter)}, // authorized_submitter
        ${BigInt(f.downstreamActionCommitment)}, // downstream_action_commitment
        ${BigInt(f.executionConstraintsFlags)},
        ${BigInt(f.lockedOutputBinding0)},
        ${BigInt(f.lockedOutputBinding1)},
        ${BigInt(f.lockedOutputBinding2)},
        ${BigInt(s.policyDataHash)},
        nonce,
        ${BigInt(f.validUntilSeconds)},
        pubkey_x,
        pubkey_y,
        signature,
        ${BigInt(s.blindingFactor)},
    );
}
`;

fs.writeFileSync(path.join(ERC, "circuits-noir/auth/src/vector_test.nr"), out);
console.log("wrote circuits-noir/auth/src/vector_test.nr");
