// Single-source constants codegen for the ERC reference implementation.
// Reads scripts/constants.json and emits:
//   circuits/common/domain_tags.circom        (Circom surface)
//   circuits-noir/common/src/constants.nr     (Noir surface)
//   contracts/src/generated/ErcConstants.sol  (Solidity surface)
//   sdk/src/generated/constants.ts            (TypeScript surface)
//   assets/domain_tags.json                   (cross-check asset)
// If assets/deployment.json exists (Task 11), also emits:
//   contracts/src/generated/CanonicalAddresses.sol
//   sdk/src/generated/addresses.ts
// Run: node scripts/gen_constants.js

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { keccak_256 } from "@noble/hashes/sha3.js";
import { sha256 } from "@noble/hashes/sha2.js";
import { poseidon, P } from "./lib/poseidon2.mjs";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ERC = path.resolve(HERE, "..");
const CFG = JSON.parse(fs.readFileSync(path.join(HERE, "constants.json"), "utf8"));

const utf8 = (s) => new TextEncoder().encode(s);
const hex = (b) => "0x" + Array.from(b, (x) => x.toString(16).padStart(2, "0")).join("");

// EIP-55 checksum so Solidity accepts address literals.
function toChecksumAddress(address) {
  const addr = address.toLowerCase().replace(/^0x/, "");
  const hashHex = hex(keccak_256(utf8(addr))).slice(2);
  let out = "0x";
  for (let i = 0; i < addr.length; i++) {
    out += parseInt(hashHex[i], 16) >= 8 ? addr[i].toUpperCase() : addr[i];
  }
  return out;
}

const tags = {};
for (const [name, ctx] of Object.entries(CFG.contexts)) {
  const h = keccak_256(utf8(CFG.domainPrefix + ctx));
  tags[name] = BigInt(hex(h)) % P;
}

const DUMMY = poseidon(tags.OWNER_NULLIFIER_KEY_HASH_DOMAIN, BigInt(CFG.dummyOwnerNullifierKeyPreimage));
const SUITE_ID = hex(keccak_256(utf8(CFG.suiteString)));
const REGISTRY_ID = hex(keccak_256(utf8(CFG.registryIdString)));
const PARAM_ASSET = fs.readFileSync(path.join(ERC, "assets/poseidon2_bn254_t4_rf8_rp56.json"));
const POSEIDON_PARAMETERS_DIGEST = hex(sha256(PARAM_ASSET));

// --- Circom ---
{
  const lines = [
    "// Auto-generated by erc/scripts/gen_constants.js — do not edit.",
    `// keccak256("${CFG.domainPrefix}<context>") mod p_bn254`,
    "",
    "pragma circom 2.0.0;",
    "",
  ];
  for (const name of Object.keys(CFG.contexts)) {
    lines.push(`function ${name}() { return ${tags[name].toString()}; }`);
  }
  lines.push(`function DUMMY_OWNER_NULLIFIER_KEY_HASH() { return ${DUMMY.toString()}; }`);
  for (const [k, v] of Object.entries(CFG.scalars)) {
    lines.push(`function ${k}() { return ${v}; }`);
  }
  fs.writeFileSync(path.join(ERC, "circuits/common/domain_tags.circom"), lines.join("\n") + "\n");
}

// --- Noir ---
{
  const nrBytes32 = (bytes) => {
    const rows = [];
    for (let i = 0; i < 32; i += 8) {
      rows.push(
        "    " +
          Array.from(bytes.slice(i, i + 8), (b) => "0x" + b.toString(16).padStart(2, "0")).join(", ") +
          ",",
      );
    }
    return rows.join("\n");
  };
  const domainTypeHash = keccak_256(
    utf8("EIP712Domain(string name,string version,uint256 chainId,address verifyingContract)"),
  );
  const nameHash = keccak_256(utf8(CFG.eip712DomainName));
  const versionHash = keccak_256(utf8(CFG.eip712DomainVersion));
  const intentTypeHash = keccak_256(utf8(CFG.eip712IntentTypeString));
  const lines = [
    "// Auto-generated by erc/scripts/gen_constants.js - do not edit.",
    `// Domain tags: keccak256("${CFG.domainPrefix}<context>") mod p_bn254.`,
    "",
    `pub global COMMITMENT_TREE_DEPTH: u32 = ${CFG.scalars.COMMITMENT_TREE_DEPTH};`,
    `pub global IDENTITY_TREE_DEPTH: u32 = ${CFG.scalars.IDENTITY_TREE_DEPTH};`,
    `pub global POLICY_SET_DEPTH: u32 = ${CFG.scalars.POLICY_SET_DEPTH};`,
    "",
    `pub global TRANSFER_OP: Field = ${CFG.scalars.TRANSFER_OP};`,
    `pub global WITHDRAWAL_OP: Field = ${CFG.scalars.WITHDRAWAL_OP};`,
    "",
    "pub global ADDRESS_BITS: u32 = 160;",
    "pub global AMOUNT_BITS: u32 = 248;",
    "pub global VALID_UNTIL_BITS: u32 = 32;",
    "pub global EXECUTION_CONSTRAINTS_FLAGS_BITS: u32 = 32;",
    "",
    `pub global LOCK_OUTPUT_BINDING_0: Field = ${CFG.scalars.LOCK_OUTPUT_BINDING_0};`,
    `pub global LOCK_OUTPUT_BINDING_1: Field = ${CFG.scalars.LOCK_OUTPUT_BINDING_1};`,
    `pub global LOCK_OUTPUT_BINDING_2: Field = ${CFG.scalars.LOCK_OUTPUT_BINDING_2};`,
    "",
    `pub global DUMMY_OWNER_NULLIFIER_KEY_PREIMAGE: Field = ${CFG.dummyOwnerNullifierKeyPreimage};`,
    `pub global DUMMY_OWNER_NULLIFIER_KEY_HASH: Field = ${DUMMY.toString()};`,
    "",
  ];
  for (const name of Object.keys(CFG.contexts)) {
    lines.push(`pub global ${name}: Field = ${tags[name].toString()};`);
  }
  lines.push("");
  lines.push("// EIP-712 constants for the Appendix A reference auth profile.");
  lines.push(`// keccak256("EIP712Domain(string name,string version,uint256 chainId,address verifyingContract)")`);
  lines.push("pub global EIP712_DOMAIN_TYPE_HASH: [u8; 32] = [");
  lines.push(nrBytes32(domainTypeHash));
  lines.push("];");
  lines.push(`// keccak256("${CFG.eip712DomainName}")`);
  lines.push("pub global EIP712_NAME_HASH: [u8; 32] = [");
  lines.push(nrBytes32(nameHash));
  lines.push("];");
  lines.push(`// keccak256("${CFG.eip712DomainVersion}")`);
  lines.push("pub global EIP712_VERSION_HASH: [u8; 32] = [");
  lines.push(nrBytes32(versionHash));
  lines.push("];");
  lines.push("// keccak256 of the Appendix A PrivateTransferIntent type string");
  lines.push("pub global EIP712_INTENT_TYPE_HASH: [u8; 32] = [");
  lines.push(nrBytes32(intentTypeHash));
  lines.push("];");
  fs.writeFileSync(path.join(ERC, "circuits-noir/common/src/constants.nr"), lines.join("\n") + "\n");
}

// --- Solidity ---
{
  const lines = [
    "// SPDX-License-Identifier: CC0-1.0",
    "pragma solidity ^0.8.24;",
    "",
    "// Auto-generated by erc/scripts/gen_constants.js - do not edit.",
    `// Domain tags: uint256(keccak256("${CFG.domainPrefix}<context>")) mod p.`,
    "library ErcConstants {",
    `    uint256 internal constant P =`,
    `        ${P.toString()};`,
    "",
  ];
  for (const name of Object.keys(CFG.contexts)) {
    lines.push(`    uint256 internal constant ${name} =`);
    lines.push(`        ${tags[name].toString()};`);
  }
  lines.push(`    uint256 internal constant DUMMY_OWNER_NULLIFIER_KEY_HASH =`);
  lines.push(`        ${DUMMY.toString()};`);
  lines.push("");
  for (const [k, v] of Object.entries(CFG.scalars)) {
    lines.push(`    uint256 internal constant ${k} = ${v};`);
  }
  lines.push("");
  lines.push(`    bytes32 internal constant SUITE_ID = ${SUITE_ID};`);
  lines.push(`    bytes32 internal constant REGISTRY_ID = ${REGISTRY_ID};`);
  lines.push(`    bytes32 internal constant POSEIDON_PARAMETERS_DIGEST = ${POSEIDON_PARAMETERS_DIGEST};`);
  lines.push(`    string internal constant OUTPUT_NOTE_DATA_SUITE = "${CFG.suiteString}";`);
  lines.push(`    string internal constant REGISTRY_ID_STRING = "${CFG.registryIdString}";`);
  lines.push("}");
  fs.writeFileSync(path.join(ERC, "contracts/src/generated/ErcConstants.sol"), lines.join("\n") + "\n");
}

// --- TypeScript ---
{
  const lines = [
    "// Auto-generated by erc/scripts/gen_constants.js - do not edit.",
    `// Domain tags: keccak256("${CFG.domainPrefix}<context>") mod p_bn254.`,
    "",
    `export const DOMAIN_PREFIX = "${CFG.domainPrefix}";`,
    `export const OUTPUT_NOTE_DATA_SUITE = "${CFG.suiteString}";`,
    `export const REGISTRY_ID_STRING = "${CFG.registryIdString}";`,
    `export const SUITE_ID = "${SUITE_ID}" as const;`,
    `export const REGISTRY_ID = "${REGISTRY_ID}" as const;`,
    `export const HKDF_SALT_LABEL = "${CFG.hkdfSaltLabel}";`,
    `export const HKDF_INFO_LABEL = "${CFG.hkdfInfoLabel}";`,
    `export const POSEIDON_PARAMETERS_DIGEST = "${POSEIDON_PARAMETERS_DIGEST}" as const;`,
    `export const CREATE2_FACTORY = "${CFG.createTwoFactory}" as const;`,
    "",
  ];
  for (const name of Object.keys(CFG.contexts)) {
    lines.push(`export const ${name} = ${tags[name].toString()}n;`);
  }
  lines.push(`export const DUMMY_OWNER_NULLIFIER_KEY_HASH = ${DUMMY.toString()}n;`);
  lines.push("");
  for (const [k, v] of Object.entries(CFG.scalars)) {
    lines.push(`export const ${k} = ${v}n;`);
  }
  fs.mkdirSync(path.join(ERC, "sdk/src/generated"), { recursive: true });
  fs.writeFileSync(path.join(ERC, "sdk/src/generated/constants.ts"), lines.join("\n") + "\n");
}

// --- JSON asset ---
{
  const out = { domainPrefix: CFG.domainPrefix, tags: {}, dummyOwnerNullifierKeyHash: "0x" + DUMMY.toString(16), suiteId: SUITE_ID, registryId: REGISTRY_ID, poseidonParametersDigest: POSEIDON_PARAMETERS_DIGEST };
  for (const name of Object.keys(CFG.contexts)) out.tags[name] = "0x" + tags[name].toString(16);
  fs.writeFileSync(path.join(ERC, "assets/domain_tags.json"), JSON.stringify(out, null, 2) + "\n");
}

// --- Canonical addresses (once deployment.json exists) ---
const DEPLOYMENT = path.join(ERC, "assets/deployment.json");
if (fs.existsSync(DEPLOYMENT)) {
  const dep = JSON.parse(fs.readFileSync(DEPLOYMENT, "utf8"));
  const sol = [
    "// SPDX-License-Identifier: CC0-1.0",
    "pragma solidity ^0.8.24;",
    "",
    "// Auto-generated by erc/scripts/gen_constants.js from assets/deployment.json - do not edit.",
    "// Imported ONLY by pools, scripts, and tests - never by the singletons themselves,",
    "// so singleton bytecode stays address-independent.",
    "library CanonicalAddresses {",
    `    address internal constant CREATE2_FACTORY = ${toChecksumAddress(CFG.createTwoFactory)};`,
    `    address internal constant CANONICAL_POSEIDON_LIB_ADDRESS = ${toChecksumAddress(dep.poseidonLib.address)};`,
    `    bytes32 internal constant CANONICAL_POSEIDON_LIB_RUNTIME_CODE_HASH = ${dep.poseidonLib.runtimeCodeHash};`,
    `    address internal constant CANONICAL_PRIVACY_REGISTRY_ADDRESS = ${toChecksumAddress(dep.registry.address)};`,
    `    bytes32 internal constant CANONICAL_PRIVACY_REGISTRY_RUNTIME_CODE_HASH = ${dep.registry.runtimeCodeHash};`,
    `    bytes32 internal constant CANONICAL_PRIVACY_REGISTRY_DEPLOYMENT_SALT = ${dep.registry.salt};`,
    `    address internal constant CANONICAL_POOL_VERIFIER_ADDRESS = ${toChecksumAddress(dep.poolVerifier.address)};`,
    `    bytes32 internal constant CANONICAL_POOL_VERIFIER_RUNTIME_CODE_HASH = ${dep.poolVerifier.runtimeCodeHash};`,
    `    bytes32 internal constant CANONICAL_POOL_VERIFIER_DEPLOYMENT_SALT = ${dep.poolVerifier.salt};`,
    "}",
  ];
  fs.writeFileSync(path.join(ERC, "contracts/src/generated/CanonicalAddresses.sol"), sol.join("\n") + "\n");
  const ts = [
    "// Auto-generated by erc/scripts/gen_constants.js from assets/deployment.json - do not edit.",
    `export const CANONICAL_POSEIDON_LIB_ADDRESS = "${toChecksumAddress(dep.poseidonLib.address)}" as const;`,
    `export const CANONICAL_PRIVACY_REGISTRY_ADDRESS = "${toChecksumAddress(dep.registry.address)}" as const;`,
    `export const CANONICAL_PRIVACY_REGISTRY_RUNTIME_CODE_HASH = "${dep.registry.runtimeCodeHash}" as const;`,
    `export const CANONICAL_POOL_VERIFIER_ADDRESS = "${toChecksumAddress(dep.poolVerifier.address)}" as const;`,
    `export const CANONICAL_POOL_VERIFIER_RUNTIME_CODE_HASH = "${dep.poolVerifier.runtimeCodeHash}" as const;`,
  ];
  fs.writeFileSync(path.join(ERC, "sdk/src/generated/addresses.ts"), ts.join("\n") + "\n");
  console.log("wrote CanonicalAddresses.sol + addresses.ts from deployment.json");
} else {
  console.log("assets/deployment.json not present yet - skipped CanonicalAddresses (Task 11)");
}

console.log("wrote domain_tags.circom, constants.nr, ErcConstants.sol, constants.ts, domain_tags.json");
for (const name of Object.keys(CFG.contexts)) console.log(`  ${name} = 0x${tags[name].toString(16)}`);
console.log(`  DUMMY_OWNER_NULLIFIER_KEY_HASH = 0x${DUMMY.toString(16)}`);
