#!/usr/bin/env node
// Copy the browser prover assets (pool Groth16 wasm/zkey/vkey + Noir auth
// circuit) into app/public/prover, and generate browser-safe ABIs + deployment
// manifest into app/src/generated. Run before `vite dev` / `vite build`.

import { copyFile, mkdir, readFile, writeFile, stat } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ERC_ROOT = path.resolve(HERE, "..");
const APP = path.join(ERC_ROOT, "app");
const PROVER_DIR = path.join(APP, "public", "prover");
const GEN_DIR = path.join(APP, "src", "generated");
const OUT = path.join(ERC_ROOT, "contracts", "out");

const proverAssets = [
  {
    sources: ["build/pool/pool_js/pool.wasm", "prover-assets/pool.wasm"],
    targetName: "pool.wasm",
  },
  {
    sources: ["build/pool/pool_final.zkey", "prover-assets/pool_final.zkey"],
    targetName: "pool_final.zkey",
  },
  {
    sources: ["build/pool/pool_vkey.json", "prover-assets/pool_vkey.json"],
    targetName: "pool_vkey.json",
  },
  {
    sources: ["circuits-noir/auth/target/auth.json", "prover-assets/auth.json"],
    targetName: "auth.json",
  },
];

const abis = [
  ["ShieldedPool.sol/ShieldedPool.json", "shieldedPoolAbi"],
  ["PrivacyIdentityRegistry.sol/PrivacyIdentityRegistry.json", "registryAbi"],
  ["PublicActionRouter.sol/PublicActionRouter.json", "publicActionRouterAbi"],
  ["SelfServeAllowlistPolicyVerifier.sol/SelfServeAllowlistPolicyVerifier.json", "allowlistPolicyAbi"],
];

async function exists(p) {
  try { await stat(p); return true; } catch { return false; }
}

async function findReadableSource(sourceRelatives) {
  const attempted = [];
  let lastCause;
  for (const sourceRelative of sourceRelatives) {
    const source = path.join(ERC_ROOT, sourceRelative);
    attempted.push(sourceRelative);
    try {
      await stat(source);
      return { source, sourceRelative };
    } catch (cause) {
      lastCause = cause;
    }
  }
  throw new Error(`missing prover asset; checked ${attempted.join(", ")}; run the circuit builds first or commit erc/prover-assets`, { cause: lastCause });
}

await mkdir(PROVER_DIR, { recursive: true });
await mkdir(GEN_DIR, { recursive: true });

for (const { sources, targetName } of proverAssets) {
  const { source, sourceRelative } = await findReadableSource(sources);
  await copyFile(source, path.join(PROVER_DIR, targetName));
  console.log(`prover: ${sourceRelative} -> app/public/prover/${targetName}`);
}

const generatedAbis = path.join(GEN_DIR, "abis.ts");
const missingAbiArtifacts = [];
for (const [rel] of abis) {
  if (!(await exists(path.join(OUT, rel)))) missingAbiArtifacts.push(rel);
}

if (missingAbiArtifacts.length === 0) {
  const parts = ["// GENERATED by scripts/prepare_prover_assets.mjs — do not edit.\n"];
  for (const [rel, name] of abis) {
    const artifact = JSON.parse(await readFile(path.join(OUT, rel), "utf8"));
    parts.push(`export const ${name} = ${JSON.stringify(artifact.abi)} as const;\n`);
  }
  await writeFile(generatedAbis, parts.join("\n"));
  console.log(`abis: contracts/out -> app/src/generated/abis.ts`);
} else if (await exists(generatedAbis)) {
  console.log(`abis: kept existing app/src/generated/abis.ts; missing contracts/out artifacts: ${missingAbiArtifacts.join(", ")}`);
} else {
  throw new Error(`missing ABI artifacts (${missingAbiArtifacts.join(", ")}); run forge build or commit app/src/generated/abis.ts`);
}

// Deployment manifests (whatever chains are present).
for (const chainId of [31337, 11155111]) {
  const src = path.join(ERC_ROOT, "assets", `deployment.${chainId}.json`);
  if (await exists(src)) {
    await copyFile(src, path.join(GEN_DIR, `deployment.${chainId}.json`));
    console.log(`deployment: assets/deployment.${chainId}.json -> app/src/generated/`);
  }
}

console.log("prepare_prover_assets: done");
