#!/usr/bin/env node
// Copy the browser prover assets (pool Groth16 wasm/zkey/vkey + Noir auth
// circuit) into app/public/prover, and generate browser-safe ABIs + deployment
// manifest into app/src/generated. Run before `vite dev` / `vite build`.

import { copyFile, mkdir, readFile, writeFile, stat } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ERC_ROOT = path.resolve(HERE, "..");
const APP = path.join(ERC_ROOT, "app");
const PROVER_DIR = path.join(APP, "public", "prover");
const GEN_DIR = path.join(APP, "src", "generated");
const OUT = path.join(ERC_ROOT, "contracts", "out");

const proverAssets = [
  ["build/pool/pool_js/pool.wasm", "pool.wasm"],
  ["build/pool/pool_final.zkey", "pool_final.zkey"],
  ["build/pool/pool_vkey.json", "pool_vkey.json"],
  ["circuits-noir/auth/target/auth.json", "auth.json"],
];

const abis = [
  ["ShieldedPool.sol/ShieldedPool.json", "shieldedPoolAbi"],
  ["PrivacyIdentityRegistry.sol/PrivacyIdentityRegistry.json", "registryAbi"],
  ["PublicActionRouter.sol/PublicActionRouter.json", "publicActionRouterAbi"],
  ["SelfServeAllowlistPolicyVerifier.sol/SelfServeAllowlistPolicyVerifier.json", "allowlistPolicyAbi"],
];

async function exists(p) {
  try { await stat(p); return true; } catch { return false; }
}

await mkdir(PROVER_DIR, { recursive: true });
await mkdir(GEN_DIR, { recursive: true });

for (const [rel, name] of proverAssets) {
  const src = path.join(ERC_ROOT, rel);
  if (!(await exists(src))) {
    throw new Error(`missing prover asset ${rel}; run the circuit builds first (npm run build:pool / build:auth-honk)`);
  }
  await copyFile(src, path.join(PROVER_DIR, name));
  console.log(`prover: ${rel} -> app/public/prover/${name}`);
}

const parts = ["// GENERATED by scripts/prepare_prover_assets.mjs — do not edit.\n"];
for (const [rel, name] of abis) {
  const artifact = JSON.parse(await readFile(path.join(OUT, rel), "utf8"));
  parts.push(`export const ${name} = ${JSON.stringify(artifact.abi)} as const;\n`);
}
await writeFile(path.join(GEN_DIR, "abis.ts"), parts.join("\n"));
console.log(`abis: contracts/out -> app/src/generated/abis.ts`);

// Deployment manifests (whatever chains are present).
for (const chainId of [31337, 11155111]) {
  const src = path.join(ERC_ROOT, "assets", `deployment.${chainId}.json`);
  if (await exists(src)) {
    await copyFile(src, path.join(GEN_DIR, `deployment.${chainId}.json`));
    console.log(`deployment: assets/deployment.${chainId}.json -> app/src/generated/`);
  }
}

console.log("prepare_prover_assets: done");
