// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {PoolGroth16Verifier} from "./PoolGroth16Verifier.sol";

/// @notice Drop-in replacement for the future PROOF_VERIFY_PRECOMPILE_ADDRESS
///         (Section 5.5). Accepts the same `abi.encode(bytes proof, PublicInputs)`
///         input shape as the real precompile, returns a 32-byte
///         `uint256(0|1)`, and never reverts.
///
/// @dev    For Foundry tests, install via `vm.etch(0x..0030, code)`. The
///         contract owns no state — the verification key is embedded in the
///         child PoolGroth16Verifier contract, which itself was generated by
///         `snarkjs zkey export solidityverifier`.
contract MockPoolPrecompile {
    PoolGroth16Verifier public immutable verifier;

    /// @notice Constructor binds the per-circuit Groth16 verifier.
    constructor(PoolGroth16Verifier verifier_) {
        verifier = verifier_;
    }

    /// @notice Spec contract: 21 public inputs in declaration order.
    struct PublicInputs {
        uint256 noteCommitmentRoot;
        uint256 nullifier0;
        uint256 nullifier1;
        uint256 noteBodyCommitment0;
        uint256 noteBodyCommitment1;
        uint256 noteBodyCommitment2;
        uint256 publicAmountOut;
        uint256 publicRecipientAddress;
        uint256 publicTokenAddress;
        uint256 intentReplayId;
        uint256 registryRoot;
        uint256 validUntilSeconds;
        uint256 executionChainId;
        uint256 authPolicyRegistrationRoot;
        uint256 authPolicyRevocationRoot;
        uint256 outputNoteDataHash0;
        uint256 outputNoteDataHash1;
        uint256 outputNoteDataHash2;
        uint256 authVerifier;
        uint256 blindedAuthCommitment;
        uint256 transactionIntentDigest;
    }

    /// @notice The fallback mirrors the precompile's calling convention exactly:
    ///         calldata is the raw `abi.encode(proof, publicInputs)`, output is
    ///         a 32-byte word, and the function MUST NOT revert.
    fallback(bytes calldata input) external returns (bytes memory) {
        try this.verifyExternal(input) returns (uint256 r) {
            return abi.encode(r);
        } catch {
            return abi.encode(uint256(0));
        }
    }

    /// @notice External self-call shim so `_verify`'s `abi.decode` can be
    ///         wrapped in a try/catch. Spec §5.5 requires the precompile MUST
    ///         NOT revert; without this, malformed ABI input would propagate
    ///         a revert from `abi.decode`.
    function verifyExternal(bytes calldata input) external view returns (uint256) {
        return _verify(input);
    }

    function _verify(bytes calldata input) private view returns (uint256) {
        if (input.length < 32 + 32 + 21 * 32) return 0;

        PublicInputs memory pi;
        bytes memory proofBytes;
        (proofBytes, pi) = abi.decode(input, (bytes, PublicInputs));
        if (proofBytes.length != 256) return 0;

        // Split the 256-byte proof into Groth16 (A, B, C) elements. The byte
        // layout is the EIP-8182 / EIP-197 canonical form documented in
        // Section 5.5: A (64) || B (128, x.c1||x.c0||y.c1||y.c0) || C (64).
        uint256[2] memory pA = [_word(proofBytes, 0), _word(proofBytes, 32)];
        uint256[2][2] memory pB = [
            [_word(proofBytes, 64),  _word(proofBytes, 96)],
            [_word(proofBytes, 128), _word(proofBytes, 160)]
        ];
        uint256[2] memory pC = [_word(proofBytes, 192), _word(proofBytes, 224)];

        uint256[21] memory pub;
        pub[0]  = pi.noteCommitmentRoot;
        pub[1]  = pi.nullifier0;
        pub[2]  = pi.nullifier1;
        pub[3]  = pi.noteBodyCommitment0;
        pub[4]  = pi.noteBodyCommitment1;
        pub[5]  = pi.noteBodyCommitment2;
        pub[6]  = pi.publicAmountOut;
        pub[7]  = pi.publicRecipientAddress;
        pub[8]  = pi.publicTokenAddress;
        pub[9]  = pi.intentReplayId;
        pub[10] = pi.registryRoot;
        pub[11] = pi.validUntilSeconds;
        pub[12] = pi.executionChainId;
        pub[13] = pi.authPolicyRegistrationRoot;
        pub[14] = pi.authPolicyRevocationRoot;
        pub[15] = pi.outputNoteDataHash0;
        pub[16] = pi.outputNoteDataHash1;
        pub[17] = pi.outputNoteDataHash2;
        pub[18] = pi.authVerifier;
        pub[19] = pi.blindedAuthCommitment;
        pub[20] = pi.transactionIntentDigest;

        try verifier.verifyProof(pA, pB, pC, pub) returns (bool ok) {
            return ok ? 1 : 0;
        } catch {
            // The snarkjs verifier reverts on non-canonical public inputs, off-curve
            // points, etc. The precompile contract MUST translate every such failure
            // into uint256(0).
            return 0;
        }
    }

    function _word(bytes memory src, uint256 offset) private pure returns (uint256 w) {
        assembly {
            w := mload(add(add(src, 32), offset))
        }
    }
}
